name: Cloudflare Worker Deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "tcb-flickr-oauth/**"
      - "tcb-flickr-polling/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy OAuth Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "tcb-flickr-oauth"
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: ${{ secrets.PRE_COMMAND }}
      - name: Deploy Polling Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "tcb-flickr-polling"
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: ${{ secrets.PRE_COMMAND }}
